ca-risken/doc

docs/google/cloudsploit.md
↓のスコア修正に伴ってドキュメント更新します
https://github.com/ca-risken/google/pull/81
=> fix cloudsploit score

docs/admin/infra_aws.md
=> fix: aws installation

codebuild/multi-arch/buildspec-image.yml, codebuild/release/buildspec-image.yml
=> fix: docker hub login

mkdocs.yml
GoogleAnalyticsの設定を入れてみます
https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-analytics/
=> add: google analytics

docs/google/overview_sa.md
=> fix: gcp custom role

docs/aws/cloudsploit.md
スコア修正に伴いドキュメント更新します
https://github.com/ca-risken/aws/pull/241
=> fix: cloudsploit score

docs/admin/infra_architecture.md, docs/admin/param_aws.md, docs/admin/param_code.md, docs/admin/param_common.md, docs/admin/param_core.md, docs/admin/param_diagnosis.md, docs/admin/param_google.md, docs/admin/param_osint.md
- アーキテクチャ変更反映（Core統合、DataSourceAPI統合）
- パラメータ関連全体的に見直し
=> fix: architecture

docs/code/dependency_concept.md
dependencyのTagからrepositoryを削除します
=> remove repository tag

docs/google/overview_sa.md
GCP CloudSploitのパーミッション変更に伴いいくつか追加します。
https://github.com/aquasecurity/cloudsploit/blob/master/docs/gcp.md
=> fix: sa permissions

docs/google/cloudsploit.md
=> fix: score

docs/aws/accessanalyzer.md
=> fix: analyzer scan delay

docs/osint/domain_concept.md
=> fix: subdomain takeover

docs/google/overview_gcp.md
=> rm: gcp org

docs/admin/param_aws.md, docs/admin/param_common.md, docs/admin/param_google.md
=> rm: unused params

docs/admin/param_common.md
=> fix: dataousource api

Makefile, codebuild/buildspec.yaml, docs/admin/infra_architecture.en.md, docs/admin/infra_architecture.md, mkdocs.yml
- mkdocsのバージョン固定します（現時点の最新化）
- datasourceネームスペースに伴う修正
=> Multi lang

docs/aws/accessanalyzer.en.md, docs/aws/accessanalyzer.md
access analyzerのスコア判定の説明を修正します
=> fix: access analyzer

docs/risken/attack_flow.en.md, docs/risken/attack_flow.md
=> fix attack flow

docs/aws/adminchecker.en.md, docs/aws/adminchecker.md
=> fix: admin-checker score

docs/risken/quick_start.en.md, docs/risken/quick_start.md
URLパスを修正します。
また、遷移先にあわせてリンク表示名も修正しています。
issue: 
https://github.com/ca-risken/doc/issues/126
=> fix: url link

docs/aws/accessanalyzer.en.md, docs/aws/accessanalyzer.md
=> fix: access analyzer docs

docs/google/overview_sa.md
=> add: sa role

docs/risken/mcp.en.md, docs/risken/mcp.md, mkdocs.yml
=> add: mcp docs

docs/code/gitleaks_concept.en.md, docs/code/gitleaks_concept.md
=> fix: gitleaks version

docs/google/scc.en.md, docs/google/scc.md
=> add: scc triage

docs/azure/overview_subscription.en.md, docs/azure/overview_subscription.md
Azureのサブスクリプション登録に関する画像の指定が誤っていたのを修正します
=> fix image path

docs/azure/prowler.en.md, docs/azure/prowler.md
=> fix prowler link

.github/workflows/claude.yml, CLAUDE.md
=> add: claude code
